name: Nightly CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      POJAVPUB_KEYSTORE_PASSWORD: ${{ secrets.POJAVPUB_KEYSTORE_PASSWORD }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get LTW
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          repo: MojoLauncher/LTW
          workflow: android.yml
          workflow_conclusion: success
          name: output-aar
          path: app_pojavlauncher/libs

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create out directory
        run: mkdir out

      - name: Generate build times
        id: time
        run: |
          echo "timestamp=$(date -u '+%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "date=$(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build Nightly Release .apk
        if: github.repository_owner == 'TeamPojavLauncher' && github.ref_name == 'v3_openjdk'
        run: |
          gradle :app_pojavlauncher:assembleFullPubRelease
          mv app_pojavlauncher/build/outputs/apk/full/pubRelease/app_pojavlauncher-full-pubRelease.apk out/Pojavlauncher-nightly.apk

      - name: Release Nightly APK
        if: github.repository_owner == 'TeamPojavLauncher' && github.ref_name == 'v3_openjdk'
        uses: softprops/action-gh-release@v3
        with:
          name: "Nightly Release #${{ github.run_number }}"
          prerelease: true
          tag_name: nightly-${{ steps.time.outputs.timestamp }}
          body: |
            # PojavLauncher Nightly Build

            > **Build #${{ github.run_number }}** · ${{ steps.time.outputs.timestamp }}

            **Commit hash:** `${{ github.sha }}`
            **Branch:** `${{ github.ref_name }}`
            **Workflow:** [Run #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            **Build on (UTC):** ${{ steps.time.outputs.date }}

            ## Changes
            For detailed changes, check the commit history.

          files: |
            out/Pojavlauncher-nightly.apk
          fail_on_unmatched_files: false
          draft: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
